### ISSUE TITLE
(TASK) UI Clean up

### ISSUE THREAD

**Issue by gmulhearn** [gmulhearn/messengerSecured#1]
General clean up for smoother UI experience

# Milestones
- [ ] Auto-refresh threads on receiving new message `messengerSecured.onMessage()`
- [ ] UI for inputting 2FA rather than from CL
- [ ] Send 'message seen' message to facebook servers when thread is opened
- [ ] Redirect when accessing unaccessible URLs
