### ISSUE TITLE
(TASK) Friend Search

### ISSUE THREAD

**Issue by gmulhearn** [gmulhearn/messengerSecured#2]
Aim to implement an interface to search for friends and begin thread chat with the selected friend

# Milestones
- [ ] Create html page for the search page
- [ ] Create form for submitting search via POST
- [ ] Create a function in views.py and/or messengerSecured.py to return a formatted list of search results
- [ ] Link results to thread page
