### ISSUE TITLE
(TASK) Documentation

### ISSUE THREAD

**Issue by gmulhearn** [gmulhearn/messengerSecured#3]
Clean up existing documentation and write in-depth documentation for the system as a whole

# Milestones
- [ ] Fix existing docstrings
- [ ] Add docstrings for all functions 
- [ ] Write wiki explaining the system as a whole
