### ISSUE TITLE
(TASK) Switch to venv usage

### ISSUE THREAD

**Issue by gmulhearn** [gmulhearn/messengerSecured#4]

**Comment by gmulhearn** [comment]
Switch to virtual environment usage such that it can be used universally and simplify the installation process.

# Milestones
- [x] Create list of installed packages and python version (requirements.txt)
- [x] Create a virtual environment with required packages and python version
- [x] Test on other devices
